#!/bin/bash
USER=$1

rm "Local State"
rm Default

cd /Users/$USER/Library/Application\ Support/Google/Chrome
FILES=$(ls)

find . -iname "Profile*" | while read f; do
    echo $f
    rm -rf "$f"
done

exit 0