#!/bin/bash
USER=$1

cd /Users/$USER/Library/Application\ Support/Google/Chrome

rm "Local State"
rm -rf Default

FILES=$(ls)

find . -iname "Profile*" | while read f; do
    echo $f
    rm -rf "$f"
done

exit 0