#!/bin/bash
CLEANUP_DIR=$1
echo "Cleanup Dir: $1"

for d in ${@:2}; do
    echo "moving to $d"
    cd $d
    FILES=$(ls)
    for f in $FILES; do
        echo $f
        if ! [[ $f =~ "Cleanup" ]]; then
            mv $f $CLEANUP_DIR
        fi
    done   
done

# Remove Default Chrome Profile
rm -rf /Users/student/Library/Application\ Support/Google/Chrome/Default





